CREATE DATABASE IF NOT EXISTS `nestle_smartflow`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `nestle_smartflow`;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `audit_logs`;
DROP TABLE IF EXISTS `manager_analytics`;
DROP TABLE IF EXISTS `inventory_movements`;
DROP TABLE IF EXISTS `sales_reports`;
DROP TABLE IF EXISTS `pos_transaction_items`;
DROP TABLE IF EXISTS `pos_transactions`;
DROP TABLE IF EXISTS `delivery_earnings`;
DROP TABLE IF EXISTS `deliveries`;
DROP TABLE IF EXISTS `delivery_routes`;
DROP TABLE IF EXISTS `warehouse_tasks`;
DROP TABLE IF EXISTS `shipments`;
DROP TABLE IF EXISTS `order_items`;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS `inventory`;
DROP TABLE IF EXISTS `products`;
DROP TABLE IF EXISTS `users`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fullName` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `role` ENUM('admin', 'manager', 'warehouse_staff', 'delivery', 'retailer') NULL,
  `company` VARCHAR(255) NULL,
  `address` TEXT NULL,
  `city` VARCHAR(100) NULL,
  `state` VARCHAR(100) NULL,
  `zipCode` VARCHAR(20) NULL,
  `country` VARCHAR(100) NULL,
  `status` ENUM('active', 'inactive', 'suspended') NOT NULL DEFAULT 'active',
  `avatar` VARCHAR(255) NULL,
  `lastLogin` DATETIME NULL,
  `emailVerified` TINYINT(1) NOT NULL DEFAULT 0,
  `refreshTokens` JSON NULL,
  `payloadJson` JSON NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_email` (`email`),
  KEY `idx_users_role` (`role`),
  KEY `idx_users_status` (`status`),
  KEY `idx_users_createdAt` (`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User accounts for all SmartFlow roles';

CREATE TABLE IF NOT EXISTS `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(100) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `costPrice` DECIMAL(10,2) NULL,
  `image` VARCHAR(255) NULL,
  `weight` DECIMAL(10,2) NULL,
  `dimensions` VARCHAR(100) NULL,
  `manufacturer` VARCHAR(255) NULL,
  `expiryDate` DATE NULL,
  `barcode` VARCHAR(100) NULL,
  `loyaltyEligible` TINYINT(1) NOT NULL DEFAULT 1,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_products_sku` (`sku`),
  KEY `idx_products_category` (`category`),
  KEY `idx_products_name` (`name`),
  KEY `idx_products_isActive` (`isActive`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Product catalog';

CREATE TABLE IF NOT EXISTS `inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NOT NULL,
  `warehouseLocation` VARCHAR(100) NOT NULL,
  `rackLocation` VARCHAR(100) NULL,
  `currentStock` INT NOT NULL DEFAULT 0,
  `reorderLevel` INT NOT NULL DEFAULT 10,
  `reorderQuantity` INT NOT NULL DEFAULT 50,
  `lastStockUpdate` DATETIME NULL,
  `lastCountDate` DATE NULL,
  `status` ENUM('in_stock', 'low_stock', 'out_of_stock') NOT NULL,
  `payloadJson` JSON NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_inventory_productId` (`productId`),
  KEY `idx_inventory_warehouseLocation` (`warehouseLocation`),
  KEY `idx_inventory_status` (`status`),
  CONSTRAINT `fk_inventory_product` FOREIGN KEY (`productId`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `chk_inventory_stock_nonnegative` CHECK (`currentStock` >= 0),
  CONSTRAINT `chk_inventory_reorder_nonnegative` CHECK (`reorderLevel` >= 0),
  CONSTRAINT `chk_inventory_reorder_qty_nonnegative` CHECK (`reorderQuantity` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Inventory levels by warehouse location';

CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderId` VARCHAR(50) NOT NULL,
  `customerId` INT NOT NULL,
  `customerName` VARCHAR(255) NULL,
  `customerEmail` VARCHAR(255) NULL,
  `customerPhone` VARCHAR(20) NULL,
  `region` VARCHAR(100) NULL,
  `store` VARCHAR(255) NULL,
  `priority` ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
  `assignedToName` VARCHAR(255) NULL,
  `lastUpdatedLabel` VARCHAR(255) NULL,
  `overdue` TINYINT(1) NOT NULL DEFAULT 0,
  `blockedReason` VARCHAR(255) NULL,
  `highValue` TINYINT(1) NOT NULL DEFAULT 0,
  `preferredDeliveryWindow` VARCHAR(100) NULL,
  `deliveryZone` VARCHAR(100) NULL,
  `assignedCarrierName` VARCHAR(255) NULL,
  `trackingNumber` VARCHAR(100) NULL,
  `promoCode` VARCHAR(100) NULL,
  `cancellationReason` VARCHAR(255) NULL,
  `customerSatisfaction` VARCHAR(100) NULL,
  `timelineJson` JSON NULL,
  `relatedOrderIdsJson` JSON NULL,
  `notesJson` JSON NULL,
  `communicationLogJson` JSON NULL,
  `payloadJson` JSON NULL,
  `totalItems` INT NOT NULL DEFAULT 0,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `tax` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `shippingCost` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `discountAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `totalAmount` DECIMAL(10,2) NOT NULL,
  `status` ENUM('pending', 'processing', 'ready_to_dispatch', 'dispatched', 'delivered', 'cancelled') NOT NULL DEFAULT 'pending',
  `paymentStatus` ENUM('pending', 'completed', 'failed', 'refunded') NOT NULL DEFAULT 'pending',
  `paymentMethod` ENUM('cash', 'card', 'digital_wallet', 'mixed') NULL,
  `deliveryAddress` TEXT NOT NULL,
  `deliveryCity` VARCHAR(100) NOT NULL,
  `deliveryZipCode` VARCHAR(20) NULL,
  `deliveryPhone` VARCHAR(20) NULL,
  `preferredDeliveryDate` DATE NULL,
  `actualDeliveryDate` DATE NULL,
  `deliveryInstructions` TEXT NULL,
  `assignedWarehouseStaff` INT NULL,
  `assignedDelivery` INT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_orders_orderId` (`orderId`),
  KEY `idx_orders_customerId` (`customerId`),
  KEY `idx_orders_status` (`status`),
  KEY `idx_orders_paymentStatus` (`paymentStatus`),
  KEY `idx_orders_createdAt` (`createdAt`),
  CONSTRAINT `fk_orders_customer` FOREIGN KEY (`customerId`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_warehouse_staff` FOREIGN KEY (`assignedWarehouseStaff`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_delivery_staff` FOREIGN KEY (`assignedDelivery`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Customer orders';

CREATE TABLE IF NOT EXISTS `order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT NOT NULL,
  `productId` INT NOT NULL,
  `quantity` INT NOT NULL,
  `unitPrice` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `specialInstructions` TEXT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_order_items_orderId` (`orderId`),
  KEY `idx_order_items_productId` (`productId`),
  CONSTRAINT `fk_order_items_order` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_order_items_product` FOREIGN KEY (`productId`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_order_items_quantity_positive` CHECK (`quantity` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Order line items';

CREATE TABLE IF NOT EXISTS `shipments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shipmentId` VARCHAR(50) NOT NULL,
  `orderId` INT NOT NULL,
  `carrierName` VARCHAR(100) NOT NULL,
  `trackingNumber` VARCHAR(100) NULL,
  `status` ENUM('pending', 'picked', 'packed', 'dispatched', 'in_transit', 'delivered', 'failed') NOT NULL DEFAULT 'pending',
  `shippingCost` DECIMAL(10,2) NOT NULL,
  `weight` DECIMAL(10,2) NULL,
  `dimensions` VARCHAR(100) NULL,
  `dispatchedAt` DATETIME NULL,
  `estimatedDeliveryDate` DATE NULL,
  `actualDeliveryDate` DATE NULL,
  `shippingLabel` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shipments_shipmentId` (`shipmentId`),
  UNIQUE KEY `uk_shipments_trackingNumber` (`trackingNumber`),
  KEY `idx_shipments_orderId` (`orderId`),
  KEY `idx_shipments_status` (`status`),
  CONSTRAINT `fk_shipments_order` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Shipment and dispatch records';

CREATE TABLE IF NOT EXISTS `warehouse_tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `taskId` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NULL,
  `taskType` ENUM('pick', 'pack', 'receive', 'verify', 'dispatch') NOT NULL,
  `orderId` INT NULL,
  `assignedTo` INT NULL,
  `assignedToName` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `zone` VARCHAR(100) NULL,
  `instructionsJson` JSON NULL,
  `priority` ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
  `status` ENUM('pending', 'in_progress', 'on_hold', 'completed', 'cancelled') NOT NULL DEFAULT 'pending',
  `progressPercentage` INT NOT NULL DEFAULT 0,
  `dueDate` DATETIME NULL,
  `completedAt` DATETIME NULL,
  `notes` TEXT NULL,
  `payloadJson` JSON NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_warehouse_tasks_taskId` (`taskId`),
  KEY `idx_warehouse_tasks_taskType` (`taskType`),
  KEY `idx_warehouse_tasks_assignedTo` (`assignedTo`),
  KEY `idx_warehouse_tasks_status` (`status`),
  KEY `idx_warehouse_tasks_dueDate` (`dueDate`),
  CONSTRAINT `fk_warehouse_tasks_order` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_warehouse_tasks_assignee` FOREIGN KEY (`assignedTo`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_warehouse_tasks_progress` CHECK (`progressPercentage` >= 0 AND `progressPercentage` <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Warehouse task queue';

CREATE TABLE IF NOT EXISTS `delivery_routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `routeId` VARCHAR(50) NOT NULL,
  `startLocation` VARCHAR(255) NOT NULL,
  `endLocation` VARCHAR(255) NOT NULL,
  `startAddress` TEXT NOT NULL,
  `endAddress` TEXT NOT NULL,
  `plannedDistanceKm` DECIMAL(10,2) NOT NULL,
  `actualDistanceKm` DECIMAL(10,2) NULL,
  `deliveriesCount` INT NOT NULL DEFAULT 0,
  `plannedDurationMinutes` INT NOT NULL,
  `actualDurationMinutes` INT NULL,
  `scheduledStartTime` DATETIME NOT NULL,
  `startTime` DATETIME NULL,
  `expectedCompletionTime` DATETIME NOT NULL,
  `completionTime` DATETIME NULL,
  `performanceLabel` ENUM('Ahead of schedule', 'On schedule', 'Behind schedule') NOT NULL DEFAULT 'On schedule',
  `waypointsJson` JSON NULL,
  `stopsJson` JSON NULL,
  `optimizationSuggestionsJson` JSON NULL,
  `estimatedSavingsMinutes` INT NOT NULL DEFAULT 0,
  `currentLocationJson` JSON NULL,
  `vehicleInfo` VARCHAR(255) NOT NULL,
  `fuelStatus` VARCHAR(100) NOT NULL,
  `weather` VARCHAR(100) NOT NULL,
  `roadConditions` VARCHAR(100) NOT NULL,
  `payloadJson` JSON NULL,
  `status` ENUM('pending', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'pending',
  `priority` ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_delivery_routes_routeId` (`routeId`),
  KEY `idx_delivery_routes_status` (`status`),
  KEY `idx_delivery_routes_priority` (`priority`),
  KEY `idx_delivery_routes_scheduledStartTime` (`scheduledStartTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Delivery driver routes';

CREATE TABLE IF NOT EXISTS `deliveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deliveryId` VARCHAR(50) NOT NULL,
  `orderId` VARCHAR(50) NOT NULL,
  `shipmentId` INT NULL,
  `routeId` INT NULL,
  `trackingNumber` VARCHAR(100) NOT NULL,
  `customerName` VARCHAR(255) NOT NULL,
  `customerPhone` VARCHAR(20) NOT NULL,
  `customerEmail` VARCHAR(255) NOT NULL,
  `address` TEXT NOT NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `scheduledTime` DATETIME NOT NULL,
  `actualTime` DATETIME NULL,
  `status` ENUM('pending', 'in_transit', 'awaiting_handoff', 'delivered', 'failed', 'returned') NOT NULL DEFAULT 'pending',
  `priority` ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
  `itemsCount` INT NOT NULL DEFAULT 0,
  `weight` VARCHAR(100) NOT NULL,
  `specialInstructions` TEXT NULL,
  `proofStatus` ENUM('Proof attached', 'Proof pending') NOT NULL DEFAULT 'Proof pending',
  `overdue` TINYINT(1) NOT NULL DEFAULT 0,
  `itemsJson` JSON NULL,
  `proofJson` JSON NULL,
  `issueJson` JSON NULL,
  `historyJson` JSON NULL,
  `payloadJson` JSON NULL,
  `deliveryWindow` VARCHAR(100) NOT NULL,
  `parkingInstructions` TEXT NULL,
  `contactPerson` VARCHAR(255) NULL,
  `recipientRequirements` TEXT NULL,
  `leaveInstructions` TEXT NULL,
  `distanceFromCurrentKm` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `estimatedMinutesToReach` INT NOT NULL DEFAULT 0,
  `trafficConditions` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_deliveries_deliveryId` (`deliveryId`),
  KEY `idx_deliveries_trackingNumber` (`trackingNumber`),
  KEY `idx_deliveries_routeId` (`routeId`),
  KEY `idx_deliveries_shipmentId` (`shipmentId`),
  KEY `idx_deliveries_status` (`status`),
  KEY `idx_deliveries_createdAt` (`createdAt`),
  CONSTRAINT `fk_deliveries_shipment` FOREIGN KEY (`shipmentId`) REFERENCES `shipments` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_deliveries_route` FOREIGN KEY (`routeId`) REFERENCES `delivery_routes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Delivery execution records';

CREATE TABLE IF NOT EXISTS `delivery_earnings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `driverId` INT NOT NULL,
  `deliveryId` INT NOT NULL,
  `routeId` INT NULL,
  `baseEarnings` DECIMAL(10,2) NOT NULL,
  `distanceBonus` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `onTimeBonus` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `performanceBonus` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `specialHandlingBonus` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `deductions` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `totalEarnings` DECIMAL(10,2) NOT NULL,
  `earnedDate` DATE NOT NULL,
  `payoutDate` DATE NULL,
  `payoutStatus` ENUM('pending', 'paid', 'failed', 'refunded') NOT NULL DEFAULT 'pending',
  `paymentMethod` VARCHAR(50) NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_delivery_earnings_driverId` (`driverId`),
  KEY `idx_delivery_earnings_deliveryId` (`deliveryId`),
  KEY `idx_delivery_earnings_earnedDate` (`earnedDate`),
  KEY `idx_delivery_earnings_payoutStatus` (`payoutStatus`),
  CONSTRAINT `fk_delivery_earnings_driver` FOREIGN KEY (`driverId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_delivery_earnings_delivery` FOREIGN KEY (`deliveryId`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_delivery_earnings_route` FOREIGN KEY (`routeId`) REFERENCES `delivery_routes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Delivery earnings and payout tracking';

CREATE TABLE IF NOT EXISTS `pos_transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transactionId` VARCHAR(50) NOT NULL,
  `cashierId` INT NULL,
  `cashierName` VARCHAR(255) NULL,
  `storeLocation` VARCHAR(100) NOT NULL,
  `topProduct` VARCHAR(255) NULL,
  `totalItems` INT NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `tax` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `discount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `totalAmount` DECIMAL(10,2) NOT NULL,
  `paymentMethod` ENUM('cash', 'card', 'digital_wallet', 'mixed') NOT NULL,
  `changeAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `status` ENUM('completed', 'pending', 'cancelled', 'refunded') NOT NULL DEFAULT 'completed',
  `customerName` VARCHAR(255) NULL,
  `customerPhone` VARCHAR(20) NULL,
  `customerEmail` VARCHAR(255) NULL,
  `notes` TEXT NULL,
  `receiptPrinted` TINYINT(1) NOT NULL DEFAULT 0,
  `transactionTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `payloadJson` JSON NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pos_transactions_transactionId` (`transactionId`),
  KEY `idx_pos_transactions_cashierId` (`cashierId`),
  KEY `idx_pos_transactions_transactionTime` (`transactionTime`),
  KEY `idx_pos_transactions_status` (`status`),
  CONSTRAINT `fk_pos_transactions_cashier` FOREIGN KEY (`cashierId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Point of sale transactions';

CREATE TABLE IF NOT EXISTS `pos_transaction_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transactionId` INT NOT NULL,
  `productId` INT NOT NULL,
  `quantity` INT NOT NULL,
  `unitPrice` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pos_transaction_items_transactionId` (`transactionId`),
  KEY `idx_pos_transaction_items_productId` (`productId`),
  CONSTRAINT `fk_pos_transaction_items_transaction` FOREIGN KEY (`transactionId`) REFERENCES `pos_transactions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_pos_transaction_items_product` FOREIGN KEY (`productId`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='POS transaction line items';

CREATE TABLE IF NOT EXISTS `sales_reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reportDate` DATE NOT NULL,
  `reportType` ENUM('daily', 'weekly', 'monthly') NOT NULL,
  `region` VARCHAR(100) NULL,
  `totalOrders` INT NOT NULL DEFAULT 0,
  `totalSales` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `totalTransactions` INT NOT NULL DEFAULT 0,
  `averageOrderValue` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `averageBasketValue` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `onTimeDeliveryRate` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `failedDeliveries` INT NOT NULL DEFAULT 0,
  `returnRate` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_sales_reports_reportDate` (`reportDate`),
  KEY `idx_sales_reports_reportType` (`reportType`),
  KEY `idx_sales_reports_region` (`region`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sales summary cache';

CREATE TABLE IF NOT EXISTS `inventory_movements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NOT NULL,
  `warehouseLocation` VARCHAR(100) NOT NULL,
  `movementType` ENUM('receive', 'dispatch', 'adjust', 'sale', 'damage', 'transfer') NOT NULL,
  `quantityBefore` INT NOT NULL,
  `quantityAfter` INT NOT NULL,
  `quantityChanged` INT NOT NULL,
  `reason` VARCHAR(255) NULL,
  `referenceId` VARCHAR(100) NULL,
  `performedBy` INT NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_inventory_movements_productId` (`productId`),
  KEY `idx_inventory_movements_warehouseLocation` (`warehouseLocation`),
  KEY `idx_inventory_movements_movementType` (`movementType`),
  KEY `idx_inventory_movements_createdAt` (`createdAt`),
  CONSTRAINT `fk_inventory_movements_product` FOREIGN KEY (`productId`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_inventory_movements_user` FOREIGN KEY (`performedBy`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Inventory movement history';

CREATE TABLE IF NOT EXISTS `manager_analytics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `analyticsDate` DATE NOT NULL,
  `totalSales` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `staffProductivity` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `inventoryCoverage` INT NOT NULL DEFAULT 0,
  `openOrders` INT NOT NULL DEFAULT 0,
  `urgentOrders` INT NOT NULL DEFAULT 0,
  `lowStockItems` INT NOT NULL DEFAULT 0,
  `onTimeDeliveryRate` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_manager_analytics_analyticsDate` (`analyticsDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Cached manager dashboard analytics';

CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `action` VARCHAR(100) NOT NULL,
  `entityType` VARCHAR(100) NOT NULL,
  `entityId` INT NULL,
  `oldValue` JSON NULL,
  `newValue` JSON NULL,
  `ipAddress` VARCHAR(45) NULL,
  `userAgent` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_audit_logs_userId` (`userId`),
  KEY `idx_audit_logs_action` (`action`),
  KEY `idx_audit_logs_entityType` (`entityType`),
  KEY `idx_audit_logs_createdAt` (`createdAt`),
  CONSTRAINT `fk_audit_logs_user` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='System audit log';

CREATE TABLE IF NOT EXISTS `notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `type` ENUM('order', 'delivery', 'stock', 'task', 'system') NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  `relatedEntityType` VARCHAR(100) NULL,
  `relatedEntityId` INT NULL,
  `isRead` TINYINT(1) NOT NULL DEFAULT 0,
  `readAt` DATETIME NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_notifications_userId` (`userId`),
  KEY `idx_notifications_isRead` (`isRead`),
  KEY `idx_notifications_createdAt` (`createdAt`),
  CONSTRAINT `fk_notifications_user` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User notifications';